import MathAnimation from "../islands/MathAnimation.tsx";

export default function TestAnimationPage() {
  return (
    <div class="app-container">
      <main
        class="main-content flex flex-col items-center justify-center"
        style={{ padding: "40px" }}
      >
        <h1 class="page-title mb-4">WASM Math Animation Test</h1>
        <p class="text-gray-500 mb-8 max-w-lg text-center">
          This page tests the integration of <code>mathlikeanim-rs</code>
          running via WebAssembly. The animation below is generated by the Rust
          engine.
        </p>

        <div class="lesson-card w-full max-w-2xl">
          <MathAnimation id="test-canvas" width={800} height={450} />

          <div class="mt-4 text-center">
            <a href="/" class="btn-primary" style={{ display: "inline-block" }}>
              ← Return Home
            </a>
          </div>
        </div>
      </main>
    </div>
  );
}
